  server:
    port: 8081

  spring:
    application:
      name: AtividadeIndenpendente
    jpg:
      hibernate:
        ddl-auto: update
      show-sql: true

    datasource:
      url: jdbc:postgresql://localhost:5432/atividadeIndependente
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
