numero = int(input('Digite o número que deseje a tabuada: '))
print('-' * 12)
print('{} x {} = {}'.format(numero, 0, numero*0))
print('{} x {} = {}'.format(numero, 1, numero*1))
print('{} x {} = {}'.format(numero, 2, numero*2))
print('{} x {} = {}'.format(numero, 3, numero*3))
print('{} x {} = {}'.format(numero, 4, numero*4))
print('{} x {} = {}'.format(numero, 5, numero*5))
print('{} x {} = {}'.format(numero, 6, numero*6))
print('{} x {} = {}'.format(numero, 7, numero*7))
print('{} x {} = {}'.format(numero, 8, numero*8))
print('{} x {} = {}'.format(numero, 9, numero*9))
print('{} x {} = {}'.format(numero, 10, numero*10))
print('-' * 12)

#Vídeo de exercício: https://youtu.be/qajq3SI0QQs?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6