nome1 = str(input('Digite seu nome completo:')).strip()
nome2 = nome1.split(' ')
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}' .format(nome2[0]))
print('Seu último nome é {}' .format(nome2[-1]))
