numero = str(input('Digite seu nome completo:')).strip()
nome = numero .split()
print('Prazer em te conhcer!')
print('Seu primeiro nome é {}'.format(nome[0]))  
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))