nome = str(input('Seu nome completo:')).strip()
print('Analisando o seu nome...')
print('Seu nome em maiusculas é {}'.format(nome.upper()))
print('Seu nome em minusculas é {}'.format(nome.lower()))
print('Seu nome ao todo tem {}'.format(len(nome)- nome.count('')))
print('Seu primeiro nome é {}'.format(len(nome.find('')))
separa = nome.split()
print('Seu primeiro nome é {} ele tem {} letras'.format(separa[0],len(separa[0])))
