primeiro = int(input('Digite o primeiro termo '))
razao = int(input('Digite a razão: '))
n = int(input('Quer q vá até qual termo? '))
termo = primeiro
count = 1 
while count <= 10:
    print(f'{termo} ->', end=' ')
    termo += razao
    count += 1