nome =str(input("qual e seu nome? "))
maiuscula = (f"{nome.upper()}")
minuscula = (f"{nome.lower()}")
quantas_letras = (f"{len(nome)}")
primeiro_nome = (f"{len(nome.split.strip()[0])}")
print(maiuscula)
print(minuscula)
print(quantas_letras)
print(primeiro_nome)
