a = float(input("Digite um valor em metro:"))
print(f'a medida de {a} metros é igual a {a*10} decímetros')
print(f'a medida de {a} metros é igual a {a*100} centrímetros')
print(f'a medida de {a} metros é igual a {a*1000} milímetros')
print(f'a medida de {a} metros é igual a {a/10} decâmetros')
print(f'a medida de {a} metros é igual a {a/100} hectômetros')
print(f'a medida de {a} metros é igual a {a/1000} quilômetros')
