spring.datasource.url=jdbc:postgresql://localhost:5432/securitypro
spring.datasource.username=postgres
spring.datasource.password=postgres
api.security.token.secret=${JWT_SECRET:my-secret-key}
spring.jpa.hibernate.ddl-auto=update