nome = str(input('Digite seu nome completo : '))
print('Analisando seu nome, pfvr aguarde...')
print('Seu nome em maiúsculas è {}'.format(nome.upper()))
print('Seu nome em minùsculas è {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))