server:
  port: 8080

spring:
  application:
    name: educacaoFinanceira
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    expiration: 86400000

  app:
    pagination:
      default-page-size: 10
      max-page-size: 50