algumaCoisa = input ('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algumaCoisa))
print('Possúi espaços? ', algumaCoisa.isspace())
print('É um número? ' , algumaCoisa.isnumeric())
print('É uma palavra? ' , algumaCoisa.isalpha())
print('É letra e/ou número? ' , algumaCoisa.isalnum())
print('Só possúi letra minúscula? ' , algumaCoisa.islower())
print('Só possúi letra maiúscula? ' , algumaCoisa.isupper())