name = input('Insert your full name')
totalCharacters = (len(name))
spaces = (name.count(' '))
characters = (totalCharacters - spaces)
individualName = name.split()
print(name.upper())
print(name.lower())
print(characters)
print(individualName[0]) 