import random
aluno1= str (input('Nome do aluno: '))
aluno2= str (input('Nome do aluno: '))
aluno3= str (input('Nome do aluno: '))
aluno4= str (input('Nome do aluno: '))
print(aluno1)
print(aluno2)
print(aluno3)
print(aluno4)
sorteio= random.choice([aluno1, aluno2, aluno3, aluno4])
print(f'O aluno sorteado é {sorteio}')