numero = int(input('Informe um numero:'))
n = str(numero)
print('Analisando o numero {}'.format(numero))
print('Unidade: {}'.format(n[3]))
print('Dezena: {}'.format(n[2]))
print('Centena: {}'.format(n[1]))
print('Milhar: {}'.format)n[0]))