## **Pandas Essencial**
**Prof. Dr. Samuel Martins (@hisamuka @xavecoding)** <br/>
xavecoding: https://youtube.com/c/xavecoding <br/>

Neste tutorial, vamos aprender o essencial da biblioteca _Pandas_ para manipulação de dados.<br/><br/>

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

### Pacotes usados neste Notebook

In [878]:
# pacotes usados neste notebook
import pandas as pd

<h1>Manipulação de Dados com Pandas</h1><hr/>

<h2>1. Manipulação Básica de Datasets</h2>
<hr/>

**Dataset**: Gas Prices in Brazil: https://www.kaggle.com/matheusfreitag/gas-prices-in-brazil <br/>

Este dataset contém os **registros dos preços médios semanais dos combustíveis do Brasil entre os anos de 2004 e 2019**. <br/>
Cada *amostra (registro/linha)* consiste em um registro de preço aferido para um dado tipo de combustível em uma dada localidade do Brasil. <br/>
Alguns dos principais *atributos* (colunas) do dataset são: 'ESTADO', 'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'PREÇO MÉDIO REVENDA'.


\* O arquivo disponibilizado no Kaggle está no formato *tsv*. Embora o _pandas_ consiga abrí-lo normalmente, convertemos tal arquivo para o formato *CSV*, que é um dos formatos mais utilizados, e mudamos seu separado para ';' apenas para mostrar algumas opções da função de carregamento.

### 1.1. Importando o Dataset
Para carregar um dataset no formato csv, basta utilizar a função `read_csv` do pandas. Por padrão, ela considera _','_ como separador.

In [1073]:
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019 (2).csv', sep=';')

In [880]:
!ls ./sample_data/

 anscombe.json			        mnist_test.csv
 california_housing_test.csv	        mnist_train_small.csv
 california_housing_train.csv	        README.md
'GasPricesinBrazil_2004-2019 (2).csv'


O dataset não foi carregado corretamente pois o separador utilizado seu arquivo CSV era ';' e não a ','. <br/>
Vamos então carregá-lo corretamente:

### 1.2. Exibindo as primeiras linhas do Dataset
A função `.head()` exibe as 5 primeiras linhas do dataset/tabela/Data Frame.

In [881]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004


In [882]:
# mostrando as 10 primeiras linhas da dataframe
data.head(10)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004
6,6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,...,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062,5,2004
7,7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,...,2.000,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082,5,2004
8,8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,...,1.699,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077,5,2004
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,1.700,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004


### 1.3 Informações do Dataset e Elementos Chave

### 1.3.1 Informações gerais sobre o Dataset

In [883]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Unnamed: 0                     106823 non-null  int64  
 1   DATA INICIAL                   106823 non-null  object 
 2   DATA FINAL                     106823 non-null  object 
 3   REGIÃO                         106823 non-null  object 
 4   ESTADO                         106823 non-null  object 
 5   PRODUTO                        106823 non-null  object 
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64  
 7   UNIDADE DE MEDIDA              106823 non-null  object 
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA          

A primeira coluna da tabela, chamada _'Unnamed: 0'_, parece não significar nada. Na verdade, ela parece ser os **índices** da tabela, que foram salvos como uma _coluna_.<br/>
Veremos jajá como **remover tal coluna**.

Outro ponto é que, aparentemente, nenhum atributo/coluna possui valores nulos (_null_), uma vez que o número de registros do dataframe e os números de valores _non-null_ é de **106823**. <br/>
Mas, veremos que não é bem assim para esse caso.

### 1.3.2 Data Frame
Todo dataset carregado (dados estruturados) é um `Data Frame`: 'Tabela' bi-dimensional, de tamanho mutável, com dados potencialmente heterogêneos. <br/>

In [884]:
type(data)

pandas.core.frame.DataFrame

Podemos acessar as **dimensões do Data Frame** (número de linhas x número de colunas) utilizando o atributo `.shape` do Data Frame.

In [885]:
data.shape

(106823, 21)

In [886]:
print(f'O dataset possui {data.shape[0]} linhas/observações/registros e {data.shape[1]} colunas/atributos/variaveis.')

O dataset possui 106823 linhas/observações/registros e 21 colunas/atributos/variaveis.


#### **Criando um DataFrame**

Podemos criar um DataFrame a partir de um _dicionário_, onde cada **chave** possui uma **lista de elementos de igual tamanho**.<br/>
As **chaves** representam as **colunas** e **cada um dos valores de sua lista** representa o **valor da linha** correspondente para aquela coluna.

In [887]:
personagens_df = pd.DataFrame ({
    'nome': ['Luke Skywalker, Yoda, Palpatine'],
    'idade': ['16, 1000, 70'],
    'peso': ['70.5, 15.2, 60.1'],
    'eh jedi': ['True, True, False']

})

In [888]:
personagens_df

,nome,idade,peso,eh jedi
0,"Luke Skywalker, Yoda, Palpatine","16, 1000, 70","70.5, 15.2, 60.1","True, True, False"


In [889]:
personagens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   nome     1 non-null      object
 1   idade    1 non-null      object
 2   peso     1 non-null      object
 3   eh jedi  1 non-null      object
dtypes: object(4)
memory usage: 164.0+ bytes


In [1071]:
personagens_df.columns

Index(['NOME', 'IDADE', 'PESO', 'EH_JEDI'], dtype='object')

#### **VEJA MAIS**
Criando um Data Frame a partir de um dicionário: https://www.geeksforgeeks.org/how-to-create-dataframe-from-dictionary-in-python-pandas/

#### **Renomeando as colunas de um DataFrame**
**===>** O método `DataFrame.columns` retorna uma ";lista" com os **nomes de todas as colunas** do data frame.

In [891]:
type(personagens_df.columns)

pandas.core.indexes.base.Index

In [892]:
list(personagens_df.columns)

['nome', 'idade', 'peso', 'eh jedi']

<br/>

**===>** Para **renomear colunas** do data frame, utilize o método `DataFrame.rename`, que retorna uma _cópia_ do data frame com as as colunas renomeadas:

In [893]:
personagens_df

,nome,idade,peso,eh jedi
0,"Luke Skywalker, Yoda, Palpatine","16, 1000, 70","70.5, 15.2, 60.1","True, True, False"


In [894]:
personagens_df_renomeado = personagens_df.rename(columns={
    'nome': 'Nome Completo',
    'idade': 'Idade',

})

In [895]:
personagens_df_renomeado

,Nome Completo,Idade,peso,eh jedi
0,"Luke Skywalker, Yoda, Palpatine","16, 1000, 70","70.5, 15.2, 60.1","True, True, False"


In [896]:
personagens_df

,nome,idade,peso,eh jedi
0,"Luke Skywalker, Yoda, Palpatine","16, 1000, 70","70.5, 15.2, 60.1","True, True, False"


Para renomear o _próprio_ data frame em questão, utilize o parâmetro `inplace=True`:

In [897]:
personagens_df.rename(columns={'nome': 'Nome Completo','idade': 'Idade'}, inplace=True)

In [898]:
personagens_df

,Nome Completo,Idade,peso,eh jedi
0,"Luke Skywalker, Yoda, Palpatine","16, 1000, 70","70.5, 15.2, 60.1","True, True, False"


<br/>

**===>** Uma outra forma de **renomear todas as listas** de um data frame é passar uma _lista_ com os novos nomes das colunas para o atributo `DataFrame.columns`:

In [899]:
personagens_df.columns = ['NOME','IDADE','PESO', 'EH_JEDI']

In [900]:
personagens_df

,NOME,IDADE,PESO,EH_JEDI
0,"Luke Skywalker, Yoda, Palpatine","16, 1000, 70","70.5, 15.2, 60.1","True, True, False"


### 1.3.3 Series

Array uni-dimensional com os dados e rótulos de um eixo.

In [901]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004


In [902]:
# selecionando uma coluna inteira
data['ESTADO']

,ESTADO
0,DISTRITO FEDERAL
1,GOIAS
2,MATO GROSSO
3,MATO GROSSO DO SUL
4,ALAGOAS
...,...
106818,RIO GRANDE DO NORTE
106819,RIO GRANDE DO SUL
106820,SANTA CATARINA
106821,SAO PAULO


In [903]:
# só funciona se não tiver espaços ou caracteres
data.ESTADO

,ESTADO
0,DISTRITO FEDERAL
1,GOIAS
2,MATO GROSSO
3,MATO GROSSO DO SUL
4,ALAGOAS
...,...
106818,RIO GRANDE DO NORTE
106819,RIO GRANDE DO SUL
106820,SANTA CATARINA
106821,SAO PAULO


In [904]:
type(data['ESTADO'])

pandas.core.series.Series

In [905]:
data.iloc[1]

,1
Unnamed: 0,1
DATA INICIAL,2004-05-09
DATA FINAL,2004-05-15
REGIÃO,CENTRO OESTE
ESTADO,GOIAS
PRODUTO,ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS,387
UNIDADE DE MEDIDA,R$/l
PREÇO MÉDIO REVENDA,1.162
DESVIO PADRÃO REVENDA,0.114


In [906]:
pd.Series([5.5, 6.0, 9.5])

,0
0,5.5
1,6.0
2,9.5


#### **Criando uma Series**

Podemos criar um DataFrame a partir de uma lista de elementos.

In [907]:
pd.Series([5.5, 6.0, 9.5], index = ['prova 1', 'prova 2', 'projeto'], name ='Notas do Luke Skywalker' )

,Notas do Luke Skywalker
prova 1,5.5
prova 2,6.0
projeto,9.5


Podemos alterar o **nome dos índices** (veremos melhor jajá) e o **nome da Series** (o que ela representa):

#### **VEJA MAIS**
https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html

### 1.3.4 Atribuindo Dados

In [908]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019


#### 1.3.4.1 Atribuindo constantes

In [909]:
produto_view = data['PRODUTO'] # não é uma cópia
produto_view

,PRODUTO
0,ETANOL HIDRATADO
1,ETANOL HIDRATADO
2,ETANOL HIDRATADO
3,ETANOL HIDRATADO
4,ETANOL HIDRATADO
...,...
106818,GNV
106819,GNV
106820,GNV
106821,GNV


In [910]:
produto_copy_bkp = data['PRODUTO'].copy() # Retorna uma cópia da coluna "produto"
produto_copy_bkp

,PRODUTO
0,ETANOL HIDRATADO
1,ETANOL HIDRATADO
2,ETANOL HIDRATADO
3,ETANOL HIDRATADO
4,ETANOL HIDRATADO
...,...
106818,GNV
106819,GNV
106820,GNV
106821,GNV


In [911]:
data['PRODUTO'] = 'Combustivel'
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Combustivel,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Combustivel,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Combustivel,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Combustivel,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Combustivel,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004


In [912]:
produto_view

,PRODUTO
0,ETANOL HIDRATADO
1,ETANOL HIDRATADO
2,ETANOL HIDRATADO
3,ETANOL HIDRATADO
4,ETANOL HIDRATADO
...,...
106818,GNV
106819,GNV
106820,GNV
106821,GNV


In [913]:
produto_copy_bkp

,PRODUTO
0,ETANOL HIDRATADO
1,ETANOL HIDRATADO
2,ETANOL HIDRATADO
3,ETANOL HIDRATADO
4,ETANOL HIDRATADO
...,...
106818,GNV
106819,GNV
106820,GNV
106821,GNV


#### 1.3.4.2 Atribuindo listas ou series

In [914]:
nrows, ncols = data.shape
nrows, ncols

(106823, 21)

In [915]:
novos_produtos = [f'Combustivel {i}' for i in range(nrows) ]
len(novos_produtos)

106823

In [916]:
# a quantidade de elementos na lista "novos_produtos" é igual ao número de linhas do dataframe
data['PRODUTO'] = novos_produtos

In [917]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Combustivel 0,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Combustivel 1,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Combustivel 2,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Combustivel 3,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Combustivel 4,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,Combustivel 106818,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,Combustivel 106819,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,Combustivel 106820,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,Combustivel 106821,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019


In [918]:
print(produto_view)
print('\n')
print(produto_copy_bkp)

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object


0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object


In [919]:
# voltando para o produto original
data['PRODUTO'] = produto_copy_bkp # produto_copy_bkp é uma Series

In [920]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019


#### 1.3.4.3 Criando novas colunas
Para **criar uma nova coluna** em um data frame, basta atribuirmos uma _lista/Series de valores_ a uma **nova 'chave'** do data frame. <br/>

**PS:** A _quantidade de valores_ da lista precisa ser **igual** ao _número de linhas/registros_ do data frame.

In [921]:
# criando uma coluna a partir do valor constante/default
# todas as linhas terão o mesmo valor para esta nova coluna
data ['coluna sem nocao'] = 'DEFAULT'
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.818,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT


In [922]:
data['coluna a partir de lista'] = range(data.shape[0])

In [923]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821


In [1072]:
# Para atribuir o mesmo valor a todas as linhas, atribua um escalar (valor único)
data['nova_coluna_valor_unico'] = '1, 2, 3'

# Para atribuir valores diferentes, a lista deve ter o mesmo número de elementos que o DataFrame
# Por exemplo, se você quisesse atribuir os números 1, 2, 3 e NaN para o resto (exemplo hipotético):
# import numpy as np
# valores = ['1', '2', '3'] + [np.nan] * (data.shape[0] - 3)
# data['nova_coluna_lista'] = valores

<br/>

Outro exemplo:

In [925]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3"
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3"
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3"
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3"
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3"


In [926]:
data['PREÇO MÉDIA REVENDA (dólares)'] = data['PREÇO MÉDIO REVENDA'] *6.0

In [927]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0,2.756,2.756,0,6,2019,DEFAULT,106818,"1, 2, 3",21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,"1, 2, 3",20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,"1, 2, 3",17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,"1, 2, 3",18.120


**PS:** Obviamente, a lógica correta em converter o preço dos combustíveis em reais para dólares não é considerar uma taxa de câmbio fixa, uma vez que cada preço foi aferido em um momento diferente.

### 1.3.4 Índices

Todo Data Frame possui **índices**, que não são considerado colunas da tabela. Tais índices são comumente **númericos**, de 0 a num_linhas-1, mas também podem ser **textuais (rótulos/labels)**.

In [928]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0,2.756,2.756,0,6,2019,DEFAULT,106818,"1, 2, 3",21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,"1, 2, 3",20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,"1, 2, 3",17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,"1, 2, 3",18.120


In [929]:
data.index

RangeIndex(start=0, stop=106823, step=1)

Use `list(data.index)` ou `data.index.to_list()` para converter um RangeIndex para uma python list.

#### **Exemplo de Data Frame com Índices Textuais (labels)**

In [930]:

pesquisa_de_satisfacao = pd.DataFrame({
    'bom': [50, 21, 100],
    'ruim': [131, 2, 30],
    'pessimo': [30, 20, 1]
}, index=['XboxOne', 'Playstation4', 'Switch'])

In [931]:
pesquisa_de_satisfacao.head()

,bom,ruim,pessimo
XboxOne,50,131,30
Playstation4,21,2,20
Switch,100,30,1


In [932]:
pesquisa_de_satisfacao.index

Index(['XboxOne', 'Playstation4', 'Switch'], dtype='object')

### 1.4 Selecionando uma ou mais amostras (Indexação)

In [933]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


#### **==>  Index-based selection (seleção baseada em Índices)**
Mostrando linhas específicas de um DataFrame:

`iloc`: seleciona elementos do Dataframe, baseado em seu **índice (número)** --> row-first, column-second

**Selecionando uma amostra/linha:**

In [934]:
# selecionando a linha 1
data.iloc[1]

,1
Unnamed: 0,1
DATA INICIAL,2004-05-09
DATA FINAL,2004-05-15
REGIÃO,CENTRO OESTE
ESTADO,GOIAS
PRODUTO,ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS,387
UNIDADE DE MEDIDA,R$/l
PREÇO MÉDIO REVENDA,1.162
DESVIO PADRÃO REVENDA,0.114


**Selecionando múltiplias amostras/linhas:**

In [935]:
# selecionando linhas de 0 a 5
data.iloc[:6]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,"1, 2, 3",8.298


In [936]:
# selecionando linhas de 10 a 15
data.iloc[10:16]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10,"1, 2, 3",9.438
11,11,2004-05-09,2004-05-15,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,131,R$/l,1.276,0.116,...,0.078,0.7119,1.1386,0.083,5,2004,DEFAULT,11,"1, 2, 3",7.656
12,12,2004-05-09,2004-05-15,NORDESTE,SERGIPE,ETANOL HIDRATADO,57,R$/l,1.301,0.109,...,0.052,0.8267,1.1059,0.053,5,2004,DEFAULT,12,"1, 2, 3",7.806
13,13,2004-05-09,2004-05-15,NORTE,ACRE,ETANOL HIDRATADO,33,R$/l,1.805,0.134,...,0.171,0.767,1.2992,0.153,5,2004,DEFAULT,13,"1, 2, 3",10.830
14,14,2004-05-09,2004-05-15,NORTE,AMAPA,ETANOL HIDRATADO,15,R$/l,1.785,0.035,...,0.167,0.8339,1.4912,0.122,5,2004,DEFAULT,14,"1, 2, 3",10.710
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15,"1, 2, 3",9.468


In [937]:
# selecionando as linhas de indice 1, 5, 10, 15
data.iloc[[1, 5, 10, 15]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,"1, 2, 3",8.298
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10,"1, 2, 3",9.438
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15,"1, 2, 3",9.468


In [938]:
# selecionando as linahas do indices 5, 1, 15, 10
data.iloc[[5, 1, 15, 10]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,"1, 2, 3",8.298
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15,"1, 2, 3",9.468
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10,"1, 2, 3",9.438


In [939]:
# retornar o valor da linha de indice 1, coluna 4 ('ESTADO')
data.iloc[1, 4]

'GOIAS'

In [940]:
# e assim por diante!

#### **==>  Label-based selection (seleção baseadas em Rótulos)**

`loc`: seleciona elementos do Dataframe, baseado em seus **rótulos** --> row-first, column-second

In [941]:
pesquisa_de_satisfacao

,bom,ruim,pessimo
XboxOne,50,131,30
Playstation4,21,2,20
Switch,100,30,1


In [942]:
pesquisa_de_satisfacao.iloc[0]

,XboxOne
bom,50
ruim,131
pessimo,30


In [943]:
# retorna o valor do indice 0
pesquisa_de_satisfacao.iloc[0, 1]

np.int64(131)

In [944]:
pesquisa_de_satisfacao.loc['XboxOne']

,XboxOne
bom,50
ruim,131
pessimo,30


In [945]:
# NÃO FUNCIONA
pesquisa_de_satisfacao.loc['XboxOne']

,XboxOne
bom,50
ruim,131
pessimo,30


In [946]:
pesquisa_de_satisfacao


,bom,ruim,pessimo
XboxOne,50,131,30
Playstation4,21,2,20
Switch,100,30,1


In [947]:
# retorna o valor da linha  'Playstation'
pesquisa_de_satisfacao.loc['Playstation4', 'ruim']

np.int64(2)

In [948]:
# selecionando as linhas dos indices 'XboxOne', 'Switch'
pesquisa_de_satisfacao.loc[['XboxOne', 'Switch']]

,bom,ruim,pessimo
XboxOne,50,131,30
Switch,100,30,1


In [949]:
# retorna todas as linhas e apenas colunas com rotulos 'bom' e 'pessimo'
pesquisa_de_satisfacao[['bom', 'pessimo']]

,bom,pessimo
XboxOne,50,30
Playstation4,21,20
Switch,100,1


In [950]:
pesquisa_de_satisfacao.loc[:, ['bom', 'pessimo']]

,bom,pessimo
XboxOne,50,30
Playstation4,21,20
Switch,100,1


OBSERVAÇÃO

In [951]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [952]:
data.iloc[1]

,1
Unnamed: 0,1
DATA INICIAL,2004-05-09
DATA FINAL,2004-05-15
REGIÃO,CENTRO OESTE
ESTADO,GOIAS
PRODUTO,ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS,387
UNIDADE DE MEDIDA,R$/l
PREÇO MÉDIO REVENDA,1.162
DESVIO PADRÃO REVENDA,0.114


In [953]:
data.loc[1]

,1
Unnamed: 0,1
DATA INICIAL,2004-05-09
DATA FINAL,2004-05-15
REGIÃO,CENTRO OESTE
ESTADO,GOIAS
PRODUTO,ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS,387
UNIDADE DE MEDIDA,R$/l
PREÇO MÉDIO REVENDA,1.162
DESVIO PADRÃO REVENDA,0.114


### 1.5 Selecionando um ou mais atributos (colunas)

In [954]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [955]:
# retornando a coluna 'estado'
data['ESTADO']

,ESTADO
0,DISTRITO FEDERAL
1,GOIAS
2,MATO GROSSO
3,MATO GROSSO DO SUL
4,ALAGOAS
...,...
106818,RIO GRANDE DO NORTE
106819,RIO GRANDE DO SUL
106820,SANTA CATARINA
106821,SAO PAULO


In [956]:
data.ESTADO

,ESTADO
0,DISTRITO FEDERAL
1,GOIAS
2,MATO GROSSO
3,MATO GROSSO DO SUL
4,ALAGOAS
...,...
106818,RIO GRANDE DO NORTE
106819,RIO GRANDE DO SUL
106820,SANTA CATARINA
106821,SAO PAULO


In [957]:
data.loc[:, 'ESTADO']

,ESTADO
0,DISTRITO FEDERAL
1,GOIAS
2,MATO GROSSO
3,MATO GROSSO DO SUL
4,ALAGOAS
...,...
106818,RIO GRANDE DO NORTE
106819,RIO GRANDE DO SUL
106820,SANTA CATARINA
106821,SAO PAULO


In [958]:
# usando . só funciona sem  caracteres
data['DATA INICIAL']

,DATA INICIAL
0,2004-05-09
1,2004-05-09
2,2004-05-09
3,2004-05-09
4,2004-05-09
...,...
106818,2019-06-23
106819,2019-06-23
106820,2019-06-23
106821,2019-06-23


In [959]:
# selecionando varias colunas
data[['PRODUTO', 'ESTADO', 'REGIÃO']]

,PRODUTO,ESTADO,REGIÃO
0,ETANOL HIDRATADO,DISTRITO FEDERAL,CENTRO OESTE
1,ETANOL HIDRATADO,GOIAS,CENTRO OESTE
2,ETANOL HIDRATADO,MATO GROSSO,CENTRO OESTE
3,ETANOL HIDRATADO,MATO GROSSO DO SUL,CENTRO OESTE
4,ETANOL HIDRATADO,ALAGOAS,NORDESTE
...,...,...,...
106818,GNV,RIO GRANDE DO NORTE,NORDESTE
106819,GNV,RIO GRANDE DO SUL,SUL
106820,GNV,SANTA CATARINA,SUL
106821,GNV,SAO PAULO,SUDESTE


Como o rótulo da coluna 'DATA INICIAL' **possui espaço**, não é possível acessá-la como método: `data.DATA INICIAL`

### 1.6 Removendo um Atributo (Coluna) do Data Frame

Como vimos anteriormente, o atributo 'Unnamed: 0' parece ser um **ruído** em nosso dataset. Desta maneira, vamos eliminá-lo,

In [960]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [961]:
# deleta no próprio dataframe a coluna de rótulo
del data['Unnamed: 0']

In [962]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,0,2.756,2.756,0,6,2019,DEFAULT,106818,"1, 2, 3",21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,"1, 2, 3",20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,"1, 2, 3",17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,"1, 2, 3",18.120


### 1.7 Salvando um Data Frame

Para salvarmos um Data Frame para um **arquivo CSV**, basta usarmos o método `.to_csv`. <br/>
Por padrão, esse método **salva os índices da tabela como uma coluna no CSV**.<br/>
Como no geral tais índices são números de 0 a n-1, não há necessidade para isso (veja que removemos anteriormente a coluna 'Unnamed: 0' que foi justamente esse caso).<br/>
Desta forma, utilize o parâmetro: `index=False`.

Por padrão, o método utilizará a ',' como separador das colunas. Caso queira alterá-lo, utilize o parâmetro `sep`.

In [963]:
data.to_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado.csv', index=False)

### 1.8 Seleção Condicional: Filtrando amostras

Durante nossas análise exploratórias, frequentemente filtraremos nossas amostras, a partir de certas **condições**, para fins de análise mais específica. <br/>
Existem algumas maneiras de fazermos tal filtragem. Antes disso, vamos carregar nosso dataset pré-processado que salvamos no item anterior.

In [964]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [965]:
data['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

#### **Selecionando apenas os preços dos Postos de São Paulo**

##### **==> Alternativa 1: Seleção Condicional (Comparações diretas)**

O código abaixo retorna uma ***Series ('array') de booleans***, com o número de linhas (amostras) do Data Frame, que informa os registros de preços dos postos do _estado de São Paulo_ (True).

In [966]:
data['ESTADO'] == 'SAO PAULO'

,ESTADO
0,False
1,False
2,False
3,False
4,False
...,...
106818,False
106819,False
106820,False
106821,True


In [967]:
selecao = data['ESTADO'] == 'SAO PAULO'

In [968]:
selecao

,ESTADO
0,False
1,False
2,False
3,False
4,False
...,...
106818,False
106819,False
106820,False
106821,True


In [969]:
type(selecao)

pandas.core.series.Series

In [970]:
selecao.shape

(106823,)

In [971]:
data.shape

(106823, 24)

Para **filtrarmos** os registros de postos do estado de São Paulo:

In [972]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


O resultado é um Data Frame com _apenas_ os registros desejados após a **filtragem**.<br/>
Podemos ainda utilizar o método `loc` para o mesmo fim:

In [973]:
data.loc[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


##### **==> Alternativa 2: Utilizando o método `query`**

`query` filtra linhas de um DataFrame baseado em uma **query (pergunta)**.

In [974]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [975]:
data.query('ESTADO == "SAO PAULO"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


<br/>

Uma boa prática é **salvar o Data Frame filtrado em uma nova variável**. Isso simplifica a complexidade do código para futuras análise feita para os postos de São Paulo.

In [976]:
postos_sp = data.query('ESTADO == "SAO PAULO"')

In [977]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


In [978]:
type(postos_sp)

pandas.core.frame.DataFrame

In [979]:
postos_sp.shape

(4263, 24)

In [980]:
postos_sp.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364


In [981]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


resetando indices

In [982]:
postos_sp.reset_index()

,index,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
1,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
2,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
3,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
4,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
4259,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
4260,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
4261,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


In [983]:
postos_sp.reset_index(drop=True)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


In [984]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


In [985]:
postos_sp.reset_index(drop=True, inplace=True)

In [986]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


In [987]:
postos_sp = data.query('ESTADO == "SAO PAULO"').reset_index(drop=True)

In [988]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,"1, 2, 3",4.938
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,"1, 2, 3",5.322
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,"1, 2, 3",5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,"1, 2, 3",20.688
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,"1, 2, 3",21.444
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358


#### **Selecionando registros de postos do Rio de Janeiro com Preços acima de 2 reais**

In [989]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [990]:
data['ESTADO'] == 'RIO DE JANEIRO'

,ESTADO
0,False
1,False
2,False
3,False
4,False
...,...
106818,False
106819,False
106820,False
106821,False


In [991]:
data['PREÇO MÉDIO REVENDA'] > 2.0

,PREÇO MÉDIO REVENDA
0,False
1,False
2,False
3,False
4,False
...,...
106818,True
106819,True
106820,True
106821,True


In [992]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA'] > 2.0)
selecao

,0
0,False
1,False
2,False
3,False
4,False
...,...
106818,False
106819,False
106820,False
106821,False


In [993]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,...,0.11,1.31,2.1358,0.061,2,2006,DEFAULT,2501,"1, 2, 3",12.168
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,...,0.117,1.438,2.2801,0.064,3,2006,DEFAULT,2528,"1, 2, 3",12.750
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,...,0.134,1.43,2.3454,0.071,3,2006,DEFAULT,2555,"1, 2, 3",12.978
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,...,0.14,1.438,2.2925,0.072,3,2006,DEFAULT,2582,"1, 2, 3",12.996
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,...,0.133,1.438,2.2513,0.068,3,2006,DEFAULT,2609,"1, 2, 3",13.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,...,0.119,2.886,3.5162,0.038,6,2019,DEFAULT,106718,"1, 2, 3",21.414
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,...,0.127,2.9772,3.5388,0.04,6,2019,DEFAULT,106745,"1, 2, 3",22.182
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,"1, 2, 3",29.568
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,"1, 2, 3",390.060


Note que o resultado da seleção continua sendo uma _Series de booleans_ com o _mesmo número de linhas/amostras do DataFrame_, de modo que cada linha possuirá um valor booleano indicando se o posto é do Rio de Janeiro e o preço aferido do combustível é maior que 2 reais (True) ou não.

O símbolo **&** significa **AND** na comparação. Essa nomenclatura do python/pandas é diferente das nomenclaturas tradicionais (&&). <br/>
Similarmente:
- **|** representa o **OR** (não é ||)
- **~** representa o **NOT** (não é !)

Alternativamente, poderíamos usar o método `query` para fazermos tal seleção. Porém, isso não é possível especificamente para esse caso, pois o rótulo da coluna 'PREÇO MÉDIO REVENDA' possui caracteres inválidos para o método (cedilha, acentos)

In [994]:
# Não funciona
# data.query('ESTADO=="RIO DE JANEIRO" and PREÇO MÉDIO REVENDA > 2')

**Aprofundando mais ainda**

A primeira comparação `(data['ESTADO'] == 'RIO DE JANEIRO')` checa, linha a linha (amostra a amostra) do DataFrame, quais são aquelas cujo o estado é RIO DE JANEIRO. Nenhuma averiguação de preços é feita nesse momento. Como resultado, temos uma Series de booleans que responde **apenas** a essa "pergunta" feita.

A segunda comparação `(data['PREÇO MÉDIO REVENDA'] > 2)` checa, linha a linha (amostra a amostra) do DataFrame, quais são os registro cujo preço do combustível é maior que 2 reais. Note que essa comparação checará os postos de **TODOS os estados**. Como resultado, temos uma Series de booleans que responde **apenas** a essa "pergunta" feita.

Por fim, as duas "perguntas" são unidas pelo AND (&) que retorna a "pergunta completa" que fizemos.

Alguns podem argumentar que tal abordagem é **ineficiente**, uma vez que, para cada condição ("pergunta"), estamos varrendo todas as linhas do DataFrame. <br/>
O Pandas _tenta otimizar_ isso ao máximo por de trás dos panos. Mas, de fato, de tivermos um dataset **muito grande** (centenas de milhares de linhas), tal abordagem se tornará _lenta_.

Assim, poderíamos fazer filtragem com múltiplos condicionais em partes:

In [995]:
selecao_1 = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[selecao_1]
postos_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,...,0.173,0.326,1.263,0.22,5,2004,DEFAULT,22,"1, 2, 3",6.588
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,...,0.175,0.3257,1.2921,0.217,5,2004,DEFAULT,49,"1, 2, 3",6.552
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,...,0.166,0.38909,1.1859,0.202,5,2004,DEFAULT,76,"1, 2, 3",6.618
103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,0.799,...,0.188,0.3453,1.3667,0.221,5,2004,DEFAULT,103,"1, 2, 3",6.894
130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,0.830,...,0.198,0.4,1.3667,0.217,6,2004,DEFAULT,130,"1, 2, 3",6.990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,...,0.119,2.886,3.5162,0.038,6,2019,DEFAULT,106718,"1, 2, 3",21.414
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,...,0.127,2.9772,3.5388,0.04,6,2019,DEFAULT,106745,"1, 2, 3",22.182
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,"1, 2, 3",29.568
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,"1, 2, 3",390.060


In [996]:
selecao_2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2.0
selecao_2

,PREÇO MÉDIO REVENDA
22,False
49,False
76,False
103,False
130,False
...,...
106718,True
106745,True
106772,True
106799,True


In [997]:
postos_rj_preco_maior_que_2 = postos_rj[selecao_2]
postos_rj_preco_maior_que_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,...,0.11,1.31,2.1358,0.061,2,2006,DEFAULT,2501,"1, 2, 3",12.168
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,...,0.117,1.438,2.2801,0.064,3,2006,DEFAULT,2528,"1, 2, 3",12.750
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,...,0.134,1.43,2.3454,0.071,3,2006,DEFAULT,2555,"1, 2, 3",12.978
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,...,0.14,1.438,2.2925,0.072,3,2006,DEFAULT,2582,"1, 2, 3",12.996
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,...,0.133,1.438,2.2513,0.068,3,2006,DEFAULT,2609,"1, 2, 3",13.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,...,0.119,2.886,3.5162,0.038,6,2019,DEFAULT,106718,"1, 2, 3",21.414
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,...,0.127,2.9772,3.5388,0.04,6,2019,DEFAULT,106745,"1, 2, 3",22.182
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,"1, 2, 3",29.568
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,"1, 2, 3",390.060


#### **Selecionando registros de postos de São Paulo ou do Rio de Janeiro com Gasolina Comum acima de 2 reais**

Podemos fazer a solução do "jeito mais lento", percorrendo o DataFrame inteiro _múltiplas vezes_:

In [998]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [999]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
selecao_2 = (data['PRODUTO'] == 'GASOLINA COMUM')
selecao_3 = (data['PREÇO MÉDIO REVENDA'] > 2)

selecao_final = selecao_1 & selecao_2 & selecao_3

In [1000]:
data_filtrado = data[selecao_final]
data_filtrado

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,0.047,1.6363,1.9594,0.026,5,2004,DEFAULT,12086,"1, 2, 3",12.270
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,0.049,1.5943,1.99651,0.027,5,2004,DEFAULT,12113,"1, 2, 3",12.240
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,0.046,1.63596,2.2137,0.026,5,2004,DEFAULT,12140,"1, 2, 3",12.252
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,...,0.055,1.64,2.21425,0.031,5,2004,DEFAULT,12167,"1, 2, 3",12.318
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,...,0.054,1.64,2.32425,0.03,6,2004,DEFAULT,12194,"1, 2, 3",12.378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,0.096,3.52,4.1007,0.025,6,2019,DEFAULT,106479,"1, 2, 3",25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,0.1,4.1972,4.6239,0.023,6,2019,DEFAULT,106623,"1, 2, 3",29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,0.096,3.502,4.0892,0.026,6,2019,DEFAULT,106629,"1, 2, 3",25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,"1, 2, 3",29.568


In [1001]:
print(data_filtrado['ESTADO'].unique())
print(data_filtrado['PRODUTO'].unique())

['RIO DE JANEIRO' 'SAO PAULO']
['GASOLINA COMUM']


<br/>

Alternativamente:

In [1002]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
postos_sp_rj = data[selecao_1]

postos_sp_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,...,0.173,0.326,1.263,0.22,5,2004,DEFAULT,22,"1, 2, 3",6.588
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,"1, 2, 3",4.608
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,...,0.175,0.3257,1.2921,0.217,5,2004,DEFAULT,49,"1, 2, 3",6.552
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,"1, 2, 3",4.596
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,...,0.166,0.38909,1.1859,0.202,5,2004,DEFAULT,76,"1, 2, 3",6.618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,"1, 2, 3",24.852
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,"1, 2, 3",390.060
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,"1, 2, 3",401.358
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,...,0.174,2.126,2.7909,0.072,6,2019,DEFAULT,106817,"1, 2, 3",18.666


In [1003]:
selecao_2 = (postos_sp_rj['PRODUTO'] == 'GASOLINA COMUM')
postos_sp_rj_gasolina = postos_sp_rj[selecao_2]

postos_sp_rj_gasolina

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,0.047,1.6363,1.9594,0.026,5,2004,DEFAULT,12086,"1, 2, 3",12.270
12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,...,0.064,1.38,1.944,0.039,5,2004,DEFAULT,12087,"1, 2, 3",11.346
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,0.049,1.5943,1.99651,0.027,5,2004,DEFAULT,12113,"1, 2, 3",12.240
12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,...,0.063,1.38,1.9319,0.038,5,2004,DEFAULT,12114,"1, 2, 3",11.328
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,0.046,1.63596,2.2137,0.026,5,2004,DEFAULT,12140,"1, 2, 3",12.252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,0.096,3.52,4.1007,0.025,6,2019,DEFAULT,106479,"1, 2, 3",25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,0.1,4.1972,4.6239,0.023,6,2019,DEFAULT,106623,"1, 2, 3",29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,0.096,3.502,4.0892,0.026,6,2019,DEFAULT,106629,"1, 2, 3",25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,"1, 2, 3",29.568


In [1004]:
selecao_3 = (data['PREÇO MÉDIO REVENDA'] > 2)
postos_sp_rj_gasolina_preco_maior_2 = postos_sp_rj_gasolina[selecao_3]
postos_sp_rj_gasolina_preco_maior_2

/tmp/ipython-input-385443829.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  postos_sp_rj_gasolina_preco_maior_2 = postos_sp_rj_gasolina[selecao_3]


,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,0.047,1.6363,1.9594,0.026,5,2004,DEFAULT,12086,"1, 2, 3",12.270
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,0.049,1.5943,1.99651,0.027,5,2004,DEFAULT,12113,"1, 2, 3",12.240
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,0.046,1.63596,2.2137,0.026,5,2004,DEFAULT,12140,"1, 2, 3",12.252
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,...,0.055,1.64,2.21425,0.031,5,2004,DEFAULT,12167,"1, 2, 3",12.318
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,...,0.054,1.64,2.32425,0.03,6,2004,DEFAULT,12194,"1, 2, 3",12.378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,0.096,3.52,4.1007,0.025,6,2019,DEFAULT,106479,"1, 2, 3",25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,0.1,4.1972,4.6239,0.023,6,2019,DEFAULT,106623,"1, 2, 3",29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,0.096,3.502,4.0892,0.026,6,2019,DEFAULT,106629,"1, 2, 3",25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,"1, 2, 3",29.568


#### **Selecionando registros dos anos de 2008, 2010 e 2012**

In [1005]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


**ALTERNATIVA 1**

In [1006]:
selecao = (data['ANO'] == 2008) | (data['ANO'] == 2010) | (data['ANO'] == 2012)
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,...,0.061,1.3892,1.6157,0.04,1,2008,DEFAULT,5098,"1, 2, 3",10.836
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,...,0.05,1.2242,1.6173,0.038,1,2008,DEFAULT,5099,"1, 2, 3",9.696
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,...,0.073,1.14,1.45,0.056,1,2008,DEFAULT,5100,"1, 2, 3",9.486
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,...,0.044,1.3247,1.5514,0.03,1,2008,DEFAULT,5101,"1, 2, 3",10.986
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,...,0.062,1.39,1.7689,0.041,1,2008,DEFAULT,5102,"1, 2, 3",10.194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,...,0.098,1.2657,1.4789,0.069,12,2012,DEFAULT,55754,"1, 2, 3",11.346
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,...,0.028,1.3997,1.4608,0.02,12,2012,DEFAULT,55755,"1, 2, 3",11.880
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,...,-,-,-,-,12,2012,DEFAULT,55756,"1, 2, 3",12.018
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,...,0.182,0.8354,1.535,0.152,12,2012,DEFAULT,55757,"1, 2, 3",9.588


**ALTERNATIVA 2**

In [1007]:
lista_de_anos = [2008, 2010, 2012]


In [1008]:
selecao = data['ANO'].isin(lista_de_anos)
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,...,0.061,1.3892,1.6157,0.04,1,2008,DEFAULT,5098,"1, 2, 3",10.836
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,...,0.05,1.2242,1.6173,0.038,1,2008,DEFAULT,5099,"1, 2, 3",9.696
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,...,0.073,1.14,1.45,0.056,1,2008,DEFAULT,5100,"1, 2, 3",9.486
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,...,0.044,1.3247,1.5514,0.03,1,2008,DEFAULT,5101,"1, 2, 3",10.986
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,...,0.062,1.39,1.7689,0.041,1,2008,DEFAULT,5102,"1, 2, 3",10.194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,...,0.098,1.2657,1.4789,0.069,12,2012,DEFAULT,55754,"1, 2, 3",11.346
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,...,0.028,1.3997,1.4608,0.02,12,2012,DEFAULT,55755,"1, 2, 3",11.880
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,...,-,-,-,-,12,2012,DEFAULT,55756,"1, 2, 3",12.018
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,...,0.182,0.8354,1.535,0.152,12,2012,DEFAULT,55757,"1, 2, 3",9.588


ALTERNATIVA 3

In [1009]:
lista_de_anos

[2008, 2010, 2012]

In [1010]:
data.query('ANO in @lista_de_anos')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,...,0.061,1.3892,1.6157,0.04,1,2008,DEFAULT,5098,"1, 2, 3",10.836
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,...,0.05,1.2242,1.6173,0.038,1,2008,DEFAULT,5099,"1, 2, 3",9.696
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,...,0.073,1.14,1.45,0.056,1,2008,DEFAULT,5100,"1, 2, 3",9.486
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,...,0.044,1.3247,1.5514,0.03,1,2008,DEFAULT,5101,"1, 2, 3",10.986
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,...,0.062,1.39,1.7689,0.041,1,2008,DEFAULT,5102,"1, 2, 3",10.194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,...,0.098,1.2657,1.4789,0.069,12,2012,DEFAULT,55754,"1, 2, 3",11.346
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,...,0.028,1.3997,1.4608,0.02,12,2012,DEFAULT,55755,"1, 2, 3",11.880
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,...,-,-,-,-,12,2012,DEFAULT,55756,"1, 2, 3",12.018
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,...,0.182,0.8354,1.535,0.152,12,2012,DEFAULT,55757,"1, 2, 3",9.588


### **Iterando com DataFrames**

#### For-each `DataFrame.iterrows()` (LENTO ==> apenas indicado para iterar pequenos conjunto de dados)

In [1011]:
data.head(10)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,0.999,...,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,"1, 2, 3",8.298
6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,1.030,...,0.068,0.7332,1.294,0.062,5,2004,DEFAULT,6,"1, 2, 3",8.718
7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,1.350,...,0.091,0.9923,1.36183,0.082,5,2004,DEFAULT,7,"1, 2, 3",9.786
8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,1.100,...,0.072,0.7577,1.2972,0.077,5,2004,DEFAULT,8,"1, 2, 3",7.704
9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,0.989,...,0.091,0.5643,1.3541,0.096,5,2004,DEFAULT,9,"1, 2, 3",7.344


In [1012]:
for index, row in data.head(10).iterrows():
    print(f"indice {index} ==> {row['ESTADO']}")

indice 0 ==> DISTRITO FEDERAL
indice 1 ==> GOIAS
indice 2 ==> MATO GROSSO
indice 3 ==> MATO GROSSO DO SUL
indice 4 ==> ALAGOAS
indice 5 ==> BAHIA
indice 6 ==> CEARA
indice 7 ==> MARANHAO
indice 8 ==> PARAIBA
indice 9 ==> PERNAMBUCO


<h2>2. Preparação dos dados</h2>
<hr/>

In [1013]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,0,2.756,2.756,0,6,2019,DEFAULT,106818,"1, 2, 3",21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,"1, 2, 3",20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,"1, 2, 3",17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,"1, 2, 3",18.120


### 2.1 Removendo amostras com valores vazios (null / nan) no dataset

In [1014]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   DATA INICIAL                   106823 non-null  object 
 1   DATA FINAL                     106823 non-null  object 
 2   REGIÃO                         106823 non-null  object 
 3   ESTADO                         106823 non-null  object 
 4   PRODUTO                        106823 non-null  object 
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64  
 6   UNIDADE DE MEDIDA              106823 non-null  object 
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  object 
 12  COEF DE VARIAÇÃO REVENDA      

De um total de 106823 observações, **não há valores null** / nan para nenhum atributo. Mas, veremos que não é bem assim neste caso específico.<br/><br/>

### 2.2 Conversão de tipos de atributos

O pandas automaticamente reconhece os tipos de dados de cada coluna. <br/>
Porém, existem alguns atributos que estão com seus tipos errados: P. ex., "PREÇO MÉDIO DISTRIBUIÇÃO" deveria ser ```float64``` e não ```object```.<br/>
Nestes casos, muito provavelmente algumas amostras têm um string ao invés de um número para tais atributos. <br/>

Os atributos *"DATA INICIAL"* e *"DATA FINAL"* deveriam ser do tipo `datetime`.

Em outros casos, alguns **atributos categóricos** são ```objects```, mas poderiam ter o tipo ```category```, que é um tipo especial do pandas. <br/>
Este tipo é necessário para se utilizar algumas funções específicas do pandas. <br/>
**Não** converteremos para este tipo por ora.

In [1015]:
data_pre = data.copy()

#### **Datas**
Como os atributos de data do datset já estão em um formato de data aceitável (YYYY-MM-DD), não precisamos forçar nenhuma conversão nesse sentido.

In [1016]:
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'])

In [1017]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object        
 3   ESTADO                         106823 non-null  object        
 4   PRODUTO                        106823 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64         
 6   UNIDADE DE MEDIDA              106823 non-null  object        
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64       
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64       
 11  

#### **Dados Numéricos**

In [1018]:
for atributo in['MARGEM MÉDIA REVENDA','PREÇO MÉDIO DISTRIBUIÇÃO','DESVIO PADRÃO DISTRIBUIÇÃO','PREÇO MÍNIMO DISTRIBUIÇÃO','PREÇO MÁXIMO DISTRIBUIÇÃO','COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
    data_pre[atributo] = pd.to_numeric(data_pre[atributo], errors='coerce')

<br/>

Note que temos vários valores ***null*** agora **após a *conversão de tipos***. Vamos checá-los com mais cuidado nos dados originais e preprocessados.

### 2.3 Limpeza de dados

In [1019]:
mask = data_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()
data_pre[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,NaN,NaN,NaN,NaN,9,2005,DEFAULT,1903,"1, 2, 3",10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,NaN,NaN,NaN,NaN,10,2005,DEFAULT,1958,"1, 2, 3",12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,NaN,NaN,NaN,NaN,10,2005,DEFAULT,2012,"1, 2, 3",13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,NaN,NaN,NaN,NaN,2,2006,DEFAULT,2497,"1, 2, 3",13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,NaN,NaN,NaN,NaN,8,2006,DEFAULT,3199,"1, 2, 3",13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106664,"1, 2, 3",20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106666,"1, 2, 3",18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106811,"1, 2, 3",19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106813,"1, 2, 3",21.288


In [1020]:
data[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,-,-,-,-,9,2005,DEFAULT,1903,"1, 2, 3",10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,-,-,-,-,10,2005,DEFAULT,1958,"1, 2, 3",12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,-,-,-,-,10,2005,DEFAULT,2012,"1, 2, 3",13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,-,-,-,-,2,2006,DEFAULT,2497,"1, 2, 3",13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,-,-,-,-,8,2006,DEFAULT,3199,"1, 2, 3",13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,-,-,-,-,6,2019,DEFAULT,106664,"1, 2, 3",20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,-,-,-,-,6,2019,DEFAULT,106666,"1, 2, 3",18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,-,-,-,-,6,2019,DEFAULT,106811,"1, 2, 3",19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,-,-,-,-,6,2019,DEFAULT,106813,"1, 2, 3",21.288


Várias amostras possuem a _string '-'_ em algumas colunas ao invés de um número de fato. Ou seja, não há aferições destes atributos para estas amostras. <br/>

<br/>

Poderíamos **preencher os valores NaN com um valor padrão**. Para isso, basta usar o método `.fillna`.

In [1021]:
data_pre_fill = data_pre.fillna(0)
data_pre_fill

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,0.000,2.7560,2.75600,0.000,6,2019,DEFAULT,106818,"1, 2, 3",21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,0.402,1.9842,2.86610,0.164,6,2019,DEFAULT,106819,"1, 2, 3",20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,0.000,1.9981,1.99810,0.000,6,2019,DEFAULT,106820,"1, 2, 3",17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,0.165,2.0179,2.50930,0.070,6,2019,DEFAULT,106821,"1, 2, 3",18.120


In [1022]:
data_pre_fill[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,0.0,0.0,0.0,0.0,9,2005,DEFAULT,1903,"1, 2, 3",10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,0.0,0.0,0.0,0.0,10,2005,DEFAULT,1958,"1, 2, 3",12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,0.0,0.0,0.0,0.0,10,2005,DEFAULT,2012,"1, 2, 3",13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,0.0,0.0,0.0,0.0,2,2006,DEFAULT,2497,"1, 2, 3",13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,0.0,0.0,0.0,0.0,8,2006,DEFAULT,3199,"1, 2, 3",13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106664,"1, 2, 3",20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106666,"1, 2, 3",18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106811,"1, 2, 3",19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106813,"1, 2, 3",21.288


In [1023]:
data_pre[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,NaN,NaN,NaN,NaN,9,2005,DEFAULT,1903,"1, 2, 3",10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,NaN,NaN,NaN,NaN,10,2005,DEFAULT,1958,"1, 2, 3",12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,NaN,NaN,NaN,NaN,10,2005,DEFAULT,2012,"1, 2, 3",13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,NaN,NaN,NaN,NaN,2,2006,DEFAULT,2497,"1, 2, 3",13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,NaN,NaN,NaN,NaN,8,2006,DEFAULT,3199,"1, 2, 3",13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106664,"1, 2, 3",20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106666,"1, 2, 3",18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106811,"1, 2, 3",19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106813,"1, 2, 3",21.288


In [1024]:
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO':10,
    'DESVIO PADRÃO DISTRIBUIÇÃO':20,
    'PREÇO MÍNIMO DISTRIBUIÇÃO':30,
    'PREÇO MÁXIMO DISTRIBUIÇÃO':'vazio'

})


In [1025]:
data_pre_fill[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,20.0,30.0,vazio,NaN,9,2005,DEFAULT,1903,"1, 2, 3",10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,20.0,30.0,vazio,NaN,10,2005,DEFAULT,1958,"1, 2, 3",12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,20.0,30.0,vazio,NaN,10,2005,DEFAULT,2012,"1, 2, 3",13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,20.0,30.0,vazio,NaN,2,2006,DEFAULT,2497,"1, 2, 3",13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,20.0,30.0,vazio,NaN,8,2006,DEFAULT,3199,"1, 2, 3",13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106664,"1, 2, 3",20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106666,"1, 2, 3",18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106811,"1, 2, 3",19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106813,"1, 2, 3",21.288


<br/>

Por mais que a função `fillna` seja interessante e útil em muitos casos, no problema em questão estamos interessados em analisar precisamente, p. ex., o **'PREÇO MÉDIO DISTRIBUIÇÃO'**.<br/>
A fim de não termos valores _sintéticos_ gerados pelo `fillna`, que possam atrapalhar nossa análise, iremos **remover (drop) todas as amostras que possuem qualquer valor NaN** para quaisquer atributos/colunas. <br/>

Para isso, basta utilizarmos o método `dropna`.

In [1026]:
data_pre.dropna(inplace=True)

In [1027]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103392 entries, 0 to 106822
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   103392 non-null  datetime64[ns]
 1   DATA FINAL                     103392 non-null  datetime64[ns]
 2   REGIÃO                         103392 non-null  object        
 3   ESTADO                         103392 non-null  object        
 4   PRODUTO                        103392 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64         
 6   UNIDADE DE MEDIDA              103392 non-null  object        
 7   PREÇO MÉDIO REVENDA            103392 non-null  float64       
 8   DESVIO PADRÃO REVENDA          103392 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           103392 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           103392 non-null  float64       
 11  MARGE

Nosso data frame agora, após essa _limpeza_, ficou mais enxuto, contentdo 103392 registros frente aos 106823 registros originais. <br/>

Essas são apenas algumas das possíveis _técnicas de limpeza de dados_. Outras estratégias, p. ex., **confiam na detecção de outliers**, que não veremos neste curso.

#### **Salvando o Dataset Preprocessado**

In [1028]:
data_pre.to_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado_final.csv', index=False)


<h2>3. Estatísticas Descritivas</h2>
<hr/>

O Pandas fornecem algumas funções/métodos ue computam certas estatísticas descritivas.

`describe`: exibe várias **estatísticas descritivas** para os _atributos_ de um dataframe ou para uma _Series_.

In [1029]:
data_final = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado_final.csv')

In [1030]:
data_final.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PREÇO MÉDIA REVENDA (dólares)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,52973.958682,64.706834
std,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,30968.261500,106.115110
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,0.000000,4.596000
25%,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,25964.750000,12.438000
50%,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,52661.500000,16.338000
75%,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,79918.250000,22.470000
max,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,106822.000000,596.142000


In [1031]:
data_final['PREÇO MÉDIO REVENDA'].describe()

,PREÇO MÉDIO REVENDA
count,103392.000000
mean,10.784472
std,17.685852
min,0.766000
25%,2.073000
50%,2.723000
75%,3.745000
max,99.357000


<br/>

Como o resultado do `describe` de um _dataframe_ é outro _dataframe_, podemos filtrar apenas algumas colunas.

In [1032]:
data_final.describe()[['PREÇO MÉDIO REVENDA']]

,PREÇO MÉDIO REVENDA
count,103392.000000
mean,10.784472
std,17.685852
min,0.766000
25%,2.073000
50%,2.723000
75%,3.745000
max,99.357000


In [1033]:
stats = data_final.describe()
stats

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PREÇO MÉDIA REVENDA (dólares)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,52973.958682,64.706834
std,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,30968.261500,106.115110
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,0.000000,4.596000
25%,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,25964.750000,12.438000
50%,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,52661.500000,16.338000
75%,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,79918.250000,22.470000
max,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,106822.000000,596.142000


In [1034]:
stats[['PREÇO MÉDIO REVENDA','PREÇO MÁXIMO REVENDA','PREÇO MÉDIO DISTRIBUIÇÃO']]

,PREÇO MÉDIO REVENDA,PREÇO MÁXIMO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO
count,103392.000000,103392.000000,103392.000000
mean,10.784472,12.458686,8.559322
std,17.685852,20.801190,13.603686
min,0.766000,0.999000,0.506000
25%,2.073000,2.330000,1.795000
50%,2.723000,3.000000,2.335000
75%,3.745000,4.150000,3.307000
max,99.357000,120.000000,83.137000


In [1035]:
stats[['PREÇO MÉDIO REVENDA','PREÇO MÁXIMO REVENDA','PREÇO MÉDIO DISTRIBUIÇÃO']].describe()

,PREÇO MÉDIO REVENDA,PREÇO MÁXIMO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO
count,8.000000,8.000000,8.000000
mean,12941.141790,12944.467360,12938.155376
std,36547.680764,36546.343970,36548.882996
min,0.766000,0.999000,0.506000
25%,2.560500,2.832500,2.200000
50%,7.264736,8.304343,5.933161
75%,38.103639,45.600893,30.987014
max,103392.000000,103392.000000,103392.000000


**Acessando apenas algumas estatísticas**

In [1036]:
stats

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PREÇO MÉDIA REVENDA (dólares)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,52973.958682,64.706834
std,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,30968.261500,106.115110
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,0.000000,4.596000
25%,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,25964.750000,12.438000
50%,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,52661.500000,16.338000
75%,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,79918.250000,22.470000
max,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,106822.000000,596.142000


In [1037]:
stats.loc[['min', 'max', 'mean']]

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PREÇO MÉDIA REVENDA (dólares)
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.00000,1.000000,2004.000000,0.000000,4.596000
max,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.78000,12.000000,2019.000000,106822.000000,596.142000
mean,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.04664,6.485067,2011.737001,52973.958682,64.706834


In [1038]:
stats.loc[['min', 'max', 'mean'], 'PREÇO MÉDIO REVENDA']

,PREÇO MÉDIO REVENDA
min,0.766000
max,99.357000
mean,10.784472


In [1039]:
stats.loc[['min', 'max', 'mean'], ['PREÇO MÉDIO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

,PREÇO MÉDIO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO
min,0.766000,0.506000
max,99.357000,83.137000
mean,10.784472,8.559322


<br/>

`mean`, `std`, `min`, etc: cada uma das estatísticas do `describe` podem ser computadas individualmente:

In [1040]:
data_final.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


#### Qual é o menor preço mínimo de revenda?

In [1041]:
data_final['PREÇO MÍNIMO REVENDA'].min()

0.59

#### Qual é a média e desvio padrão dos preços mínimos de revenda?

In [1042]:
mean = data_final['PREÇO MÍNIMO REVENDA'].mean()
std = data_final['PREÇO MÍNIMO REVENDA'].std()

print(f'A média dos preços minimos de revendas é {mean:.2} +- {std:.2}')

A média dos preços minimos de revendas é 9.3 +- 1.5e+01


#### Quais são os estados considerados?

In [1043]:
data_final['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [1044]:
sorted(data_final['ESTADO'].unique())

['ACRE',
 'ALAGOAS',
 'AMAPA',
 'AMAZONAS',
 'BAHIA',
 'CEARA',
 'DISTRITO FEDERAL',
 'ESPIRITO SANTO',
 'GOIAS',
 'MARANHAO',
 'MATO GROSSO',
 'MATO GROSSO DO SUL',
 'MINAS GERAIS',
 'PARA',
 'PARAIBA',
 'PARANA',
 'PERNAMBUCO',
 'PIAUI',
 'RIO DE JANEIRO',
 'RIO GRANDE DO NORTE',
 'RIO GRANDE DO SUL',
 'RONDONIA',
 'RORAIMA',
 'SANTA CATARINA',
 'SAO PAULO',
 'SERGIPE',
 'TOCANTINS']

#### Quantos registros (aferições) cada estado possui?

`.value_counts()`:  Conta a frequência dos valores de uma dada variável (de preferência, _categórica_).

In [1045]:
data_final['ESTADO'].value_counts()

,count
ESTADO,
BAHIA,4263
RIO DE JANEIRO,4262
SAO PAULO,4261
RIO GRANDE DO SUL,4249
PARAIBA,4240
PERNAMBUCO,4236
SERGIPE,4202
SANTA CATARINA,4164
MINAS GERAIS,4142


In [1046]:
data_final['ESTADO'].value_counts().to_frame()

,count
ESTADO,
BAHIA,4263
RIO DE JANEIRO,4262
SAO PAULO,4261
RIO GRANDE DO SUL,4249
PARAIBA,4240
PERNAMBUCO,4236
SERGIPE,4202
SANTA CATARINA,4164
MINAS GERAIS,4142


<h2>4. Executando funções para cada item de um DataFrame ou Series</h2>
<hr/>

Uma alternativa ao `for-loop` que vimos anteriormente e que é _lento_, é usarmos _funções próprias do pandas_ que **aplicam/mapeiam uma dada função a todos os elementos de um DataFrame ou Series**, retornando novos elementos "transformados".


<img src='./imagens/apply_map_applymap.png' width=300/>


Fonte: https://towardsdatascience.com/introduction-to-pandas-apply-applymap-and-map-5d3e044e93ff

In [1047]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])

In [1048]:
df

,A,B,C
Linha 1,1,10,100
Linha 2,2,20,200
Linha 3,3,30,300
Linha 4,4,40,400


`apply()`: usado para aplicar uma função ao longo de um eixo de um DataFrame ou em valores de uma Series.

<img src='./imagens/pandas_axis.jpg' width=500/>

Fonte: https://www.allthesnippets.com/browse/pandas/df_axis.html

In [1049]:
def nossa_soma(linha):
    return linha.sum()

In [1050]:
df['SOMA(A, B, C)'] = df.apply(nossa_soma, axis=1)
df

,A,B,C,"SOMA(A, B, C)"
Linha 1,1,10,100,111
Linha 2,2,20,200,222
Linha 3,3,30,300,333
Linha 4,4,40,400,444


<img src='./imagens/apply_axis_1.png' width=250/>

In [1051]:
df.loc['Linha 5'] = df.apply(nossa_soma, axis=0)
df

,A,B,C,"SOMA(A, B, C)"
Linha 1,1,10,100,111
Linha 2,2,20,200,222
Linha 3,3,30,300,333
Linha 4,4,40,400,444
Linha 5,10,100,1000,1110


<img src='./imagens/apply_axis_0.png' width=250/>

##### Usando `lambda` functions

In [1052]:
df['MÉDIA(A, B, C'] = df[['A', 'B', 'C']].apply(lambda series: series.mean(), axis=1)
df

,A,B,C,"SOMA(A, B, C)","MÉDIA(A, B, C"
Linha 1,1,10,100,111,37.0
Linha 2,2,20,200,222,74.0
Linha 3,3,30,300,333,111.0
Linha 4,4,40,400,444,148.0
Linha 5,10,100,1000,1110,370.0


In [1053]:
df['C * 2'] = df['C'].apply(lambda x: x*2)
df

,A,B,C,"SOMA(A, B, C)","MÉDIA(A, B, C",C * 2
Linha 1,1,10,100,111,37.0,200
Linha 2,2,20,200,222,74.0,400
Linha 3,3,30,300,333,111.0,600
Linha 4,4,40,400,444,148.0,800
Linha 5,10,100,1000,1110,370.0,2000


<img src='./imagens/apply_axis_1_mean.png' width=350/>

In [1054]:
df['A * 2'] = df['A'] * 2
df

,A,B,C,"SOMA(A, B, C)","MÉDIA(A, B, C",C * 2,A * 2
Linha 1,1,10,100,111,37.0,200,2
Linha 2,2,20,200,222,74.0,400,4
Linha 3,3,30,300,333,111.0,600,6
Linha 4,4,40,400,444,148.0,800,8
Linha 5,10,100,1000,1110,370.0,2000,20


<br/>

`applymap()`: usado para aplicar uma função para **cada elemento** (_element-wise_) de um DataFrame.

In [1055]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])
df

,A,B,C
Linha 1,1,10,100
Linha 2,2,20,200
Linha 3,3,30,300
Linha 4,4,40,400


In [1056]:
df.applymap(lambda x: x**2)

/tmp/ipython-input-1911323247.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x**2)


,A,B,C
Linha 1,1,100,10000
Linha 2,4,400,40000
Linha 3,9,900,90000
Linha 4,16,1600,160000


In [1057]:
df

,A,B,C
Linha 1,1,10,100
Linha 2,2,20,200
Linha 3,3,30,300
Linha 4,4,40,400


<br/>

`map()`: usado para aplicar uma função para **cada elemento** (_element-wise_) de uma _Series_.

In [1058]:
nomes = pd.Series(['João', 'Maria', 'Alice', 'Pero'])
nomes

,0
0,João
1,Maria
2,Alice
3,Pero


In [1059]:
nomes.map(lambda x: x.upper())

,0
0,JOÃO
1,MARIA
2,ALICE
3,PERO


In [1060]:
nomes

,0
0,João
1,Maria
2,Alice
3,Pero


In [1061]:
nomes.str.upper()

,0
0,JOÃO
1,MARIA
2,ALICE
3,PERO


<h2>5. Agrupamento</h2>
<hr/>

`groupby`: Usado para criar **grupo de elementos** (e.x., baseado nos valores de um atributo). <br/>
**Funções** podem então ser aplicadas para os _elementos de cada grupo_, de modo que os **resultados de cada grupo são combinados**.

In [1062]:
data_final.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [1065]:
grupos = data_final.groupby('REGIÃO')
grupos

In [1066]:
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 1

In [1067]:
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 103363, 103364, 103383]),
 'NORDESTE': array([     4,      5,      6, ..., 103385, 103387, 103391]),
 'NORTE': array([    13,     14,     15, ..., 103374, 103375, 103379]),
 'SUDESTE': array([    20,     21,     22, ..., 103377, 103386, 103390]),
 'SUL': array([    24,     25,     26, ..., 103376, 103388, 103389])}

In [1068]:
grupos.get_group('CENTRO OESTE')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
27,2004-05-16,2004-05-22,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,144,R$/l,1.271,0.039,1.060,...,0.111,0.4094,1.19310,0.135,5,2004,DEFAULT,27,"1, 2, 3",7.626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103359,2019-06-23,2019-06-29,CENTRO OESTE,DISTRITO FEDERAL,GLP,42,R$/13Kg,73.452,4.875,65.000,...,7.877,44.0000,62.82000,0.152,6,2019,DEFAULT,106787,"1, 2, 3",440.712
103361,2019-06-23,2019-06-29,CENTRO OESTE,GOIAS,GLP,209,R$/13Kg,71.968,5.381,53.000,...,4.285,45.5700,61.60000,0.075,6,2019,DEFAULT,106789,"1, 2, 3",431.808
103363,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO,GLP,95,R$/13Kg,96.691,6.835,73.000,...,8.846,61.1500,90.00000,0.115,6,2019,DEFAULT,106791,"1, 2, 3",580.146
103364,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GLP,115,R$/13Kg,72.297,8.054,59.990,...,5.109,47.0000,72.00000,0.092,6,2019,DEFAULT,106792,"1, 2, 3",433.782


In [1069]:
grupos.describe()

NÚMERO DE POSTOS PESQUISADOS                                      \
                                    count        mean         std  min    25%   
REGIÃO                                                                          
CENTRO OESTE                      14545.0  144.898453  105.699340  1.0   80.0   
NORDESTE                          35788.0  124.721834  113.110808  1.0   41.0   
NORTE                             24000.0   67.835958   52.961342  1.0   31.0   
SUDESTE                           16744.0  726.068024  787.588935  1.0  168.0   
SUL                               12315.0  366.266423  233.276285  1.0  188.0   

                                   PREÇO MÉDIO REVENDA             ...  \
                50%    75%     max               count       mean  ...   
REGIÃO                                                             ...   
CENTRO OESTE  128.0  192.0   766.0             14545.0  12.299706  ...   
NORDESTE       95.0  169.0   625.0             35788.0   9.558746  ...   
NORTE          53.0   95.0   383.0             24000.0  12.633086  ...   
SUDESTE       412.0  996.0  4167.0             16744.0   9.828218  ...   
SUL           368.0  563.0  1416.0             12315.0  10.254388  ...   

             coluna a partir de lista           PREÇO MÉDIA REVENDA (dólares)  \
                                  75%       max                         count   
REGIÃO                                                                          
CENTRO OESTE                  80299.0  106812.0                       14545.0   
NORDESTE                      79910.5  106822.0                       35788.0   
NORTE                         80343.5  106807.0                       24000.0   
SUDESTE                       79401.5  106821.0                       16744.0   
SUL                           79332.5  106820.0                       12315.0   

                                                                             
                   mean         std    min     25%     50%     75%      max  
REGIÃO                                                                       
CENTRO OESTE  73.798239  119.704635  6.582  12.684  16.866  23.166  596.142  
NORDESTE      57.352477   95.933090  5.850  11.886  15.744  21.480  477.780  
NORTE         75.798516  117.827109  7.356  14.292  17.982  25.386  523.620  
SUDESTE       58.969309   97.709682  4.596  11.262  15.321  21.435  475.152  
SUL           61.526326  101.423263  5.532  11.940  15.582  21.318  432.528  

[5 rows x 128 columns]

In [1074]:
grupos.mean(numeric_only=True)

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PREÇO MÉDIA REVENDA (dólares)
REGIÃO,,,,,,,,,,,,,,,,
CENTRO OESTE,144.898453,12.299706,0.695078,10.610077,13.993156,2.438077,0.042077,9.861629,0.692259,8.511186,11.130478,0.039288,6.483396,2011.773599,52794.848127,73.798239
NORDESTE,124.721834,9.558746,0.552230,8.375173,10.788018,2.069198,0.041247,7.489549,0.514093,6.563284,8.461956,0.047887,6.487845,2011.704454,53022.749022,57.352477
NORTE,67.835958,12.633086,0.718957,11.410176,14.448137,2.221746,0.047480,10.411340,0.442566,9.505328,11.314534,0.034485,6.488458,2011.812083,52735.865958,75.798516
SUDESTE,726.068024,9.828218,0.678608,7.966396,11.894671,2.335709,0.055126,7.492509,0.585445,6.000720,9.330476,0.060778,6.481844,2011.707895,53281.350334,58.969309
SUL,366.266423,10.254388,0.729338,8.434376,12.391134,2.283191,0.047045,7.971197,0.726774,6.443075,9.851008,0.056162,6.476736,2011.681608,53089.777913,61.526326


<br/>

Também podemos ter agrupamentos por mais de um atributo.

In [1075]:
data_final.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,"1, 2, 3",7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,"1, 2, 3",6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,"1, 2, 3",8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,"1, 2, 3",7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,"1, 2, 3",7.086


In [1076]:
data_final.groupby(['REGIÃO', 'PRODUTO']).mean(numeric_only=True)

NÚMERO DE POSTOS PESQUISADOS  \
REGIÃO       PRODUTO                                          
CENTRO OESTE ETANOL HIDRATADO                    155.514414   
             GASOLINA COMUM                      155.447352   
             GLP                                 202.113944   
             GNV                                   3.759150   
             ÓLEO DIESEL                         131.940332   
             ÓLEO DIESEL S10                      76.054545   
NORDESTE     ETANOL HIDRATADO                    154.143770   
             GASOLINA COMUM                      174.051678   
             GLP                                 127.294072   
             GNV                                  17.498068   
             ÓLEO DIESEL                         135.536185   
             ÓLEO DIESEL S10                      93.857190   
NORTE        ETANOL HIDRATADO                     47.731312   
             GASOLINA COMUM                       77.837665   
             GLP                                  91.767224   
             GNV                                   1.378601   
             ÓLEO DIESEL                          68.135956   
             ÓLEO DIESEL S10                      40.495267   
SUDESTE      ETANOL HIDRATADO                   1038.720115   
             GASOLINA COMUM                     1051.909236   
             GLP                                 757.155881   
             GNV                                  81.839493   
             ÓLEO DIESEL                         771.300955   
             ÓLEO DIESEL S10                     419.743514   
SUL          ETANOL HIDRATADO                    454.889928   
             GASOLINA COMUM                      495.972387   
             GLP                                 487.431498   
             GNV                                  21.242759   
             ÓLEO DIESEL                         364.170348   
             ÓLEO DIESEL S10                     230.283597   

                               PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  \
REGIÃO       PRODUTO                                                        
CENTRO OESTE ETANOL HIDRATADO             2.135670               0.111992   
             GASOLINA COMUM               3.077476               0.104105   
             GLP                         48.176747               2.911219   
             GNV                          1.856312               0.032635   
             ÓLEO DIESEL                  2.481286               0.081540   
             ÓLEO DIESEL S10              3.294752               0.108976   
NORDESTE     ETANOL HIDRATADO             2.320266               0.115449   
             GASOLINA COMUM               3.001887               0.108104   
             GLP                         41.966090               2.667713   
             GNV                          1.881722               0.061486   
             ÓLEO DIESEL                  2.346950               0.069301   
             ÓLEO DIESEL S10              3.041966               0.091881   
NORTE        ETANOL HIDRATADO             2.511624               0.123097   
             GASOLINA COMUM               3.149501               0.140339   
             GLP                         47.065572               2.811086   
             GNV                          2.084399               0.007749   
             ÓLEO DIESEL                  2.571048               0.105590   
             ÓLEO DIESEL S10              3.316231               0.127927   
SUDESTE      ETANOL HIDRATADO             2.163621               0.134447   
             GASOLINA COMUM               3.000565               0.122024   
             GLP                         42.081544               3.117192   
             GNV                          1.716074               0.130730   
             ÓLEO DIESEL                  2.339699               0.082670   
             ÓLEO DIESEL S10              3.056194               0.109765   
SUL         

In [1078]:
grupos.mean(numeric_only=True)

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PREÇO MÉDIA REVENDA (dólares)
REGIÃO,,,,,,,,,,,,,,,,
CENTRO OESTE,144.898453,12.299706,0.695078,10.610077,13.993156,2.438077,0.042077,9.861629,0.692259,8.511186,11.130478,0.039288,6.483396,2011.773599,52794.848127,73.798239
NORDESTE,124.721834,9.558746,0.552230,8.375173,10.788018,2.069198,0.041247,7.489549,0.514093,6.563284,8.461956,0.047887,6.487845,2011.704454,53022.749022,57.352477
NORTE,67.835958,12.633086,0.718957,11.410176,14.448137,2.221746,0.047480,10.411340,0.442566,9.505328,11.314534,0.034485,6.488458,2011.812083,52735.865958,75.798516
SUDESTE,726.068024,9.828218,0.678608,7.966396,11.894671,2.335709,0.055126,7.492509,0.585445,6.000720,9.330476,0.060778,6.481844,2011.707895,53281.350334,58.969309
SUL,366.266423,10.254388,0.729338,8.434376,12.391134,2.283191,0.047045,7.971197,0.726774,6.443075,9.851008,0.056162,6.476736,2011.681608,53089.777913,61.526326


In [1079]:
grupos['PREÇO MÉDIO REVENDA'].mean()

,PREÇO MÉDIO REVENDA
REGIÃO,
CENTRO OESTE,12.299706
NORDESTE,9.558746
NORTE,12.633086
SUDESTE,9.828218
SUL,10.254388


In [1080]:
grupos['PREÇO MÉDIO REVENDA'].describe()

,count,mean,std,min,25%,50%,75%,max
REGIÃO,,,,,,,,
CENTRO OESTE,14545.0,12.299706,19.950773,1.097,2.114,2.8110,3.8610,99.357
NORDESTE,35788.0,9.558746,15.988848,0.975,1.981,2.6240,3.5800,79.630
NORTE,24000.0,12.633086,19.637852,1.226,2.382,2.9970,4.2310,87.270
SUDESTE,16744.0,9.828218,16.284947,0.766,1.877,2.5535,3.5725,79.192
SUL,12315.0,10.254388,16.903877,0.922,1.990,2.5970,3.5530,72.088


<br/>

`.agg`: **agrega (roda)** uma série de funções para os elementos de um dataframe ou de grupos de um dataframe.

In [1081]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [None,None,None]],
                  columns=['A', 'B', 'C'])
df

,A,B,C
0,1.0,2.0,3.0
1,4.0,5.0,6.0
2,7.0,8.0,9.0
3,NaN,NaN,NaN


In [1082]:
df.agg(['sum', 'min'])

,A,B,C
sum,12.0,15.0,18.0
min,1.0,2.0,3.0


In [1083]:
grupos = data_final.groupby('REGIÃO')
grupos

In [1084]:
grupos['PREÇO MÉDIO REVENDA'].agg([ 'min', 'max'])

,min,max
REGIÃO,,
CENTRO OESTE,1.097,99.357
NORDESTE,0.975,79.630
NORTE,1.226,87.270
SUDESTE,0.766,79.192
SUL,0.922,72.088


<h2>6. Ordenação</h2>
<hr/>

In [1085]:
notas = pd.DataFrame({
    'nome': ['João', 'Maria', 'José', 'Alice'],
    'idade': [20, 21, 19, 20],
    'nota_final': [5.0, 10.0, 6.0, 10.0]
})
notas

,nome,idade,nota_final
0,João,20,5.0
1,Maria,21,10.0
2,José,19,6.0
3,Alice,20,10.0


`.sort_values()`: ordena valores ao longo de um eixo.

In [1086]:
notas.sort_values(by='nota_final')

,nome,idade,nota_final
0,João,20,5.0
2,José,19,6.0
1,Maria,21,10.0
3,Alice,20,10.0


Por padrão, o método retorna uma cópia dos dados ordenados em **ordem crescente (ascendente)**. Podemos alterar isso pelo argumento `ascending`.

In [1088]:
notas.sort_values(by='nota_final', ascending=False)

,nome,idade,nota_final
3,Alice,20,10.0
1,Maria,21,10.0
2,José,19,6.0
0,João,20,5.0


<br/>

Podemos ordenar a partir de **mais de uma coluna**:

In [1090]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True], inplace=True)

In [1091]:
notas

,nome,idade,nota_final
3,Alice,20,10.0
1,Maria,21,10.0
2,José,19,6.0
0,João,20,5.0


Ordena os registros, primeiramente, pela coluna 'nota_final' em **ordem descrente**. <br/>
Então, reordena os registros _"empatados"_, ou seja, com a **mesma nota final**, em _ordem alfabética_ (ordem crescente).

<br/>

Note que o dataframe original **não foi alterado** após a ordenação.

Para alterá-lo, use o argumento `inplace=True`:

<h2>7. Exercícios</h2>
<hr/>

Vamos aplicar os conceitos que vimos em alguns exercícios. <br/>
Para isso, utilizaremos o dataset de _preços de combustíveis no Brasil_.

Como há apenas medições de janeiro a junho para o ano de 2019, resolvemos **remover os dados** deste ano da análise.

In [1096]:
data_exercicios = data_final.query('ANO != 2019')

Note que temos um novo dataframe com 99739 linhas, mas com índices fora desse intervalo. <br/>
Acontece que os registros mantiveram seus índices originais após a query. <br/>

Para resetar os índices de _0 a num_linhas-1_, basta usarmos o método `.reset_index()`.

Os índices agora foram **resetados**. Porém, os índices antigos se transformaram em _uma nova coluna_ chamada 'index'. <br/>
Para removê-la durante o _reset_, basta passarmos o argumento `drop=True`.

In [1097]:
data_exercicios.reset_index(drop=True, inplace=True)

### 7.1 Qual a proporção de postos pesquisados para cada combustível em cada região

In [1098]:
postos_por_regiao_produto = data_exercicios.groupby(['REGIÃO', 'PRODUTO'])['NÚMERO DE POSTOS PESQUISADOS'].sum()
total_postos_por_regiao = data_exercicios.groupby('REGIÃO')['NÚMERO DE POSTOS PESQUISADOS'].sum()

proporcao_postos = postos_por_regiao_produto.div(total_postos_por_regiao, level='REGIÃO').unstack(fill_value=0)
print(proporcao_postos)

PRODUTO       ETANOL HIDRATADO  GASOLINA COMUM       GLP       GNV  \
REGIÃO                                                               
CENTRO OESTE          0.230294        0.231121  0.299611  0.001520   
NORDESTE              0.243871        0.275878  0.183225  0.020457   
NORTE                 0.152683        0.261649  0.301038  0.000201   
SUDESTE               0.268558        0.272246  0.196033  0.019220   
SUL                   0.238576        0.259123  0.253929  0.008886   

PRODUTO       ÓLEO DIESEL  ÓLEO DIESEL S10  
REGIÃO                                      
CENTRO OESTE     0.197647         0.039806  
NORDESTE         0.217078         0.059491  
NORTE            0.230268         0.054160  
SUDESTE          0.200792         0.043151  
SUL              0.191251         0.048234  


### 7.2 Como os preços da Gasolina Comum em São Paulo variaram em 2018?

In [1099]:
gasolina_sp_2018 = data_exercicios.query('ESTADO == "SAO PAULO" and PRODUTO == "GASOLINA COMUM" and ANO == 2018')
print(gasolina_sp_2018.head())

      DATA INICIAL  DATA FINAL   REGIÃO     ESTADO         PRODUTO  \
92319   2018-01-07  2018-01-13  SUDESTE  SAO PAULO  GASOLINA COMUM   
92465   2018-01-14  2018-01-20  SUDESTE  SAO PAULO  GASOLINA COMUM   
92610   2018-01-21  2018-01-27  SUDESTE  SAO PAULO  GASOLINA COMUM   
92755   2018-01-28  2018-02-03  SUDESTE  SAO PAULO  GASOLINA COMUM   
92901   2018-02-04  2018-02-10  SUDESTE  SAO PAULO  GASOLINA COMUM   

       NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
92319                          1641              R$/l                3.988   
92465                          1648              R$/l                4.002   
92610                          1648              R$/l                4.006   
92755                          1644              R$/l                4.019   
92901                          1646              R$/l                4.004   

       DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
92319                  0.156                 3.499 

In [1100]:
print(gasolina_sp_2018['PREÇO MÉDIO REVENDA'].describe())

count    52.000000
mean      4.202769
std       0.180672
min       3.970000
25%       4.008000
50%       4.202000
75%       4.336250
max       4.512000
Name: PREÇO MÉDIO REVENDA, dtype: float64


#### **Estatísticas Descritivas**

In [1101]:
print(gasolina_sp_2018['PREÇO MÉDIO REVENDA'].mean())
print(gasolina_sp_2018['PREÇO MÉDIO REVENDA'].std())

4.2027692307692295
0.18067201519301895


### 7.3 Como os preços da Gasolina Comum e do Etanol em São Paulo variaram em 2018?

In [1104]:
data_exercicios.query('(PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO") and ESTADO == "SAO PAULO" and ANO == 2018')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,nova_coluna_valor_unico,PREÇO MÉDIA REVENDA (dólares)
92238,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,2.449,...,0.092,2.1842,2.8833,0.037,1,2018,DEFAULT,95270,"1, 2, 3",16.998
92319,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,...,0.104,2.9900,3.9510,0.029,1,2018,DEFAULT,95351,"1, 2, 3",23.928
92384,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,2.399,...,0.087,2.2600,2.8471,0.034,1,2018,DEFAULT,95421,"1, 2, 3",17.208
92465,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,...,0.102,2.9900,3.9014,0.028,1,2018,DEFAULT,95502,"1, 2, 3",24.012
92529,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,2.399,...,0.095,1.6900,2.9722,0.037,1,2018,DEFAULT,95573,"1, 2, 3",17.244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99410,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,3.699,...,0.110,3.3500,3.9892,0.030,12,2018,DEFAULT,102724,"1, 2, 3",24.774
99472,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,2.149,...,0.094,2.0067,2.7443,0.040,12,2018,DEFAULT,102793,"1, 2, 3",15.864
99553,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,3.699,...,0.107,3.3500,3.9892,0.029,12,2018,DEFAULT,102874,"1, 2, 3",24.774
99617,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,2.259,...,0.097,1.9072,2.7957,0.041,12,2018,DEFAULT,102944,"1, 2, 3",15.858


<h2>8. Assuntos para continuar os estudos</h2>
<hr/>

- join
- concat
- plot
- data cleaning