spring:
  application:
    name: libraryapi
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true


# production
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false

#homologação
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/library