num = int(input('Digite um número:'))
numero = str(num)
print('Analisando o número {}'.format(num))
print('Unidades:{}'.format(numero[3])) 
print('Dezena:{}'.format(numero[2]))
print('Centena:{}'.format(numero[1]))
print('Milhar:{}'.format(numero[0]))
