a = input('digite algo: ')
print('o tipo primitivo desse valor é ', type(a)) 
print('Só tem espaços? ', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Esta em maiusculs?', a.isupper())
print('Esta em minusculas?', a.islower())
print('Esta capitalizada?', a.istitle())