nome=str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiusculas é {nome.upper()}')
print(f'Seu nome em minusculas é {nome.lower()}')
print(f'Seu nome ao todo tem ao todo {len(nome)}')
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))