listagem = ('Pão ............ R$   2.50', 'Leite .......... R$   3.80', 'Frango.......... R$   10.90', 'Bolo............ R$   12.00', 'Agua ........... R$   2.50', 'Suco ........... R$   1.50' ,'Morangos ....... R$ 5.00')
print('-' * 40)
print('     LISTA DE PREÇO      ')
print('-' * 40)
print(listagem[0])
print(listagem[1])
print(listagem[2])
print(listagem[3])
print(listagem[4])
print(listagem[5])
print(listagem[6])