print ('ATIVIDADE DO CURSO #4 DESAFIO 2')
print ('Olá usuário digite o seu nome para te dar boas vindas')
nome = input ('Qual o seu nome?')
print(f"Oi {nome} seja bem vindo(a)!")
print ('Digite os seus dados no formulário abaixo:')
dia = input ('Que dia vc nasceu?')
mês = input ('Que mês vc nasceu?')
ano = input ('Que ano vc nasceu?')
print(f"Você nasceu no dia {dia} de {mês} de {ano}. Correto?")