a=input('Digite algo: ')
print('O tipo primivo desse valor é',type(a))
print('Só tem espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Esta em naiúsculas?', a.islower())
print('está em minúsculas?',a.islower())
print('Está capitalizada?',a.istitle())