num=int(input('Digite um número:'))
print(f'{num} x 1 é: ', num*1)
print(f'{num} x 2 é: ', num*2)
print(f'{num} x 3 é: ', num*3)
print(f'{num} x 4 é: ', num*4)
print(f'{num} x 5 é: ', num*5)
print(f'{num} x 6 é: ', num*6)
print(f'{num} x 7 é: ', num*7)
print(f'{num} x 8 é: ', num*8)
print(f'{num} x 9 é: ', num*9)
print(f'{num} x 10 é: ', num*10)