nome= (input('Qual seu nome completo? '))
nomeMaiusculo= nome.upper()
nomeMinusculo= nome.lower()
nomeInespaçado= (len(nome)-nome.count(' '))
primeiroNome= nome.split( )
print(f'Seu nome é {nome} ')
print (f'Seu nome totalmente maiúsculo é {nomeMaiusculo}')
print (f'Seu nome totalmente minúsculo é {nomeMinusculo}')
print(f'Seu nome possui {nomeInespaçado } caracteres sem contar os espaços')
print (f'Seu primeiro nome possui é {primeiroNome[0]} e possui {len(primeiroNome[0])} caracteres')
