select nome, genero, profissao from clientes order by "nome" asc;
select nome, genero, profissao from clientes order by "nome" desc;
select nome from clientes where nome like '%r%';
select nome from clientes where nome like 'C%';
select nome from clientes where nome like '%a';
select nome, bairro from clientes where bairro like 'Centro';
select nome, complemento from clientes where complemento like 'A%';
select nome, genero from clientes where genero like 'F';
select nome, cpf from clientes where cpf is null;
select nome, profissao from clientes order by "profissao" asc;
select nome, nacionalidade from clientes where nacionalidade like 'Brasileira';
select nome, numero from clientes where numero  is not null;
select nome, uf from clientes where uf like 'SC';
select nome, data_nascimento from clientes where data_nascimento between '01-01-2000' and '01-01-2002';
select nome|| '-' ||  logradouro||  '-' ||  numero ||  '-' || complemento|| '-' ||  bairro||  '-' ||  municipio||  '-' ||  uf as "Cliente concatenado" from clientes;

select * from clientes;
update clientes set nome = 'Teste' where idcliente = 1;
update clientes set nome = 'Adriano', genero = 'M', numero = '241'  where idcliente= 4;
insert into clientes (idcliente, nome ) values (16, 'João');
delete from clientes where idcliente = 16;